version: '3'
services:
  node:
    build:
      context: ./my_blog_front
      dockerfile: Dockerfile
    volumes:
      - ./my_portfolio_front:/usr/src/app
    command: sh -c "cd portfolio && npm i && npm run dev"
    ports:
      - "3000:3000"